#!/usr/bin/env sh
set -x
export TZ=UTC
create_entry() {
  touch "${1}"
}

get_filename() {
  todays_date=$(date +%Y%m%d)
  journal_dir=$(dirname $0)
  echo "${journal_dir}/${todays_date}.md"
}

stream_small_amount_of_data_into_todays_entry() {
  >&2 echo "INFO: Waiting at most one second for input."
  case "$(uname -s)" in
    Darwin)
      /usr/local/opt/coreutils/libexec/gnubin/timeout 1 cat /dev/stdin >> "$(get_filename)"
      ;;
    Linux)
      timeout 1 cat /dev/stdin >> "$(get_filename)"
      ;;
    *)
      >&2 echo "Failed to find timeout."
      exit 1
      ;;
  esac
  timeout 1 cat /dev/stdin >> "$(get_filename)"
  if [ $? -eq 124 ]
  then
    if ! test -s $(get_filename)
    then
      >&2 echo "ERROR: Please provide a journal entry."
      exit 1
    else
      >&2 echo "WARNING: A journal entry was added, but this script timed out
before adding all of it. Open this file in vi and add your entry directly."
      exit 2
    fi
  fi
}

redirect_data_into_todays_entry() {
  echo "- $*" >> "$(get_filename)"
}

if ! test -f "$(get_filename)"
then
  create_entry "$(get_filename)"
fi
if [ $# -gt 0 ]
then
  redirect_data_into_todays_entry $*
else
  stream_small_amount_of_data_into_todays_entry
fi
echo "$(get_filename)"
exit 0
